/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:1234c0d7-5740-490f-825a-4d6694c97d71",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_u7Yo2hjBq",
  aws_user_pools_web_client_id: "5rcnbbr5il30uo9em4u3lolaks",
  oauth: {
    domain:
      "frontdollarcity5681af15-5681af15-staging.auth.us-east-2.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://main.d1zt027t9vz7v6.amplifyapp.com/",
    redirectSignOut: "https://main.d1zt027t9vz7v6.amplifyapp.com/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_login_mechanisms: ["EMAIL", "PREFERRED_USERNAME"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
};

export default awsmobile;
